Gemfile, Gemfile.lock, Guardfile
* Runs guard, which  runs rake
* Watches for file changes and rebuilds from middleman
* Opens a browser window on guard startup
```
bundle install
bundle exec guard
```
=> Use guard to watch, generate and open files

source/includes/task_notes.md, source/index.md
This is the endpoint for text notes. IDE notes will be deprecated.
=> Initial design for task notes

source/includes/analysis_notes.md, source/includes/analysis_sessions.md, source/index.md
THIS IS A WIP! Just creating a merge request so people can compare and view what I've done so far.
=> Analysis Notes/Sessions

source/includes/_errors.md, source/includes/authentication.md, source/includes/help.md, source/includes/introduction.md, source/includes/resources.md, source/index.md
Just cleaning up the introduction text for the API.
=> Small style changes.

source/includes/applications.md, source/includes/projects.md
* Add slug filtering to applications endpoint
* Add slug filtering to projects endpoint
* Add id to project include filter on applications endpoint
=> API v2 improvements

source/includes/projects.md
* Add missing url field.
* Add missing groups and users fields.
* Add new profile field.
=> Update project endpoint with profile

source/includes/task_updates.md, source/index.md
Added Docs for the Task Updates Endpoint. Feel free to nitpick some of the language or clarify things.
=> Document the Task Updates Endpoint

format, source/includes/applications.md, source/includes/glossary_terms.md, source/includes/library_problems.md, source/includes/library_tasks.md, source/includes/phases.md, source/includes/profiles.md, source/includes/project_roles.md, source/includes/projects.md, source/includes/report_settings.md, source/includes/task_updates.md, source/includes/tasks.md
Run the following command to run the format script:
```
./format
```
* Needs Node.js installed.
=> Format script

source/includes/business_units.md
Wait until the code is in a public release to merge.
=> Add default members field to BU

source/includes/jobs.md
We currently return email addresses.
=> The jobs endpoint should return user ids.

source/includes/tasks.md
=> Update docs for project tasks endpoint: add regulation sections

source/includes/business_units.md
- BU endpoint is now writable.
- BU GET endpoint fields updated.
Refs #SDE-2267
=> Add docs for BU endpoint

source/includes/projects.md
=> Added profile.logo_url field to projects endpoint

source/includes/tags.md, source/index.yml
=> Added tags endpoint

source/includes/projects.md
=> Add docs for task count include filter

source/includes/activity.md
=> Add log_level field to activities endpoint.

source/includes/activity.md, source/includes/business_units.md, source/includes/projects.md, source/includes/user_activity.md, source/index.yml
=> Add docs for users activity-log APIv2 endpoint.

source/includes/assigned_tasks.md, source/index.yml
=> Add docs for /users/me/tasks/

source/includes/projects.md
=> Add locked, locked_by, locked_on fields to project endpoint

source/includes/projects.md
Changed the doc to say PATCH for the project update.
=> Updated the doc for the project update

source/includes/assigned_tasks.md
- project and application_id are now returned.
- project is expandable.
Refs #SDE-2555
=> Update assigned tasks docs

source/includes/projects.md
Added description and example of new expand parameter for project creator.
Refs #SDE-2397
=> Add description of expand project creator

source/includes/applications.md
=> Add expand business unit to apiv2 applications

source/includes/analysis_notes.md, source/includes/task_notes.md
=> Task Note docs update

source/includes/users.md
=> Add group roles to users endpoint

source/includes/groups.md
=> Add create and edit docs for groups api endpoint.

source/includes/groups.md
=> Updated field needed for groups list page.

source/includes/groups.md
Add total_user_count include filter
Add all_users include filter
Add role expand filter
Refs: SDE-2916
=> Update groups api documentation.

source/includes/project_roles.md
=> Make Project Role writable

source/includes/business_units.md, source/includes/groups.md, source/includes/tasks.md
BUs Tasks, and Groups all use the UserField field, which has now
been re-worked to include a role field.
Refs: SDE-3050
=> Add roles to all fields that use the UserField.

source/includes/authentication.md, source/includes/reset_password.md, source/includes/users.md, source/index.yml
Add password reset status to the users endpoint and add password reset endpoint.
Refs #SDE-3188
=> Add password reset information and status.

source/includes/connections.md, source/includes/jobs.md
* Connector points to 'parent' of the project alm, and will be needed
for POST/PUT implementation on these endpoints.
* Will add to this PR with docs for the POST request, too. 
Refs: #SDE-3128
=> Add 'connector' field to connections api, and add docs for POST endpoints. 

source/includes/connections.md
The alias field was updated and is now optional for analysis
connection endpoint.
Refs: #SDE-3128
=> Update analaysis conneciton endpoint.

source/includes/project_roles.md
=> Added documentation for deleting project role

source/includes/project_roles.md
=> Add search and sort/order to project roles docs

source/includes/global_roles.md, source/includes/project_roles.md
+ Also fix a typo in project-roles
Refs #SDE-3021
=> Add global-roles POST/PATCH/DELETE docs

README.md, source/includes/changelog.md, source/index.yml, source/javascripts/app/_toc.js
A customer asked us to provide them with a list of what changes (in more
detail) from release to release. This is probably a good idea to
maintain. I'm sure it will be a common request. Will also help us track
our own progress on the API, and when changes were made.
=> Add a change log to the documentation.

source/includes/projects.md
=> Add task completion endpoint

source/includes/project_members.md, source/includes/projects.md
- Removes users/groups from projects endpoint.
- Adds users/groups to projects/id/members endpoint.
Refs #SDE-3324
=> Add project/id/members endpoint

source/includes/sso.md, source/index.yml
* Added docs for a bind connection test endpoint
* Added docs for a user authentication test endpoint
=> Add API docs for LDAP connection test endpoints.

source/includes/projects.md
Make include filter more descriptive.
Refs #SDE-3321
=> Add phase to description of task counts

source/includes/project_activity.md, source/index.yml
=> Add Project Activities tab for the new endpoint

source/includes/tasks.md
=> Add training data to tasks endpoint

source/includes/changelog.md, source/includes/plugins_alm.md, source/index.yml
=> Add documentation for the plugins/alm/ endpoint.

source/includes/changelog.md, source/includes/connectors.md
Update docs to reflect Connectors endpoint being writeable, and having 'params'. 
Refs: #SDE-3461, #SDE-3462
=> Update connection and connector API docs.

source/includes/changelog.md, source/includes/connections.md
=> Add include field last_job from ALM, Analysis and LDAP connection endpoints

source/includes/projects.md
=> Fix erroneous docs.

source/includes/sso.md
=> Fix documentation error on LDAP connection test endpoint

source/includes/applications.md
=> Add Project url to SimpleProjectSerializer

source/includes/changelog.md, source/includes/tasks.md
We now return an expandable updater field from the tasks endpoint.
Refs #SDE-3513
TODO:
=> Add updater to tasks endpoint.

source/includes/introduction.md
It wasn't very clear how you actually browse through the API using pagination.
TODO:
=> Add more details to the pagination documentation

source/includes/phases.md
=> Add ordinal and phase to the phase endpoint docs

source/includes/changelog.md
Add ordinal and active fields
Refs #SDE-3629
TODO:
=> Update changelog for phase endpoint

source/includes/changelog.md, source/includes/phases.md
=> Expose is_custom field to phase endpoint

source/includes/api_tokens.md, source/includes/changelog.md, source/includes/user_profile.md, source/includes/users.md, source/index.yml
=> APIv2 docs for changing password, user profile and password reset questions (feature/accounts)

source/includes/users.md
Reset Questions endpoint doesn't support Token Auth.
=> Fix authentiaction scheme on account settings endpoints

source/includes/changelog.md, source/includes/connections.md, source/includes/jobs.md
Remove start_tls
Remove some bind_password where its not required
Refs: #SDE-3743
TODO:
=> Add inaccessible to the param list

source/includes/changelog.md, source/includes/connections.md
* Renamed deactivation to deactivate_groupless_users
* Removed ldap_method
* Added ldap_start_tls
* Added docs for deactivate_stale_users
Refs #SDE-3778,#SDE-3767
TODO:
=> Fix LDAP Connection Documentation

source/includes/changelog.md, source/includes/connections.md
=> Use group id instead of group name for group_mapping in LDAP Connections

source/includes/changelog.md, source/includes/users.md
=> Add docs for /users/me/ endpoint

source/includes/connections.md, source/includes/connectors.md
Also remove query paramters that do not exist.
Add 'project' as a query parameter.
Refs: #SDE-3748
=> Update integrations:  system field is a dictionary.

source/includes/business_units.md, source/includes/changelog.md
=> Expose persist_phases field on BU endpoint

source/includes/phases.md
Refs #SDE-3772
TODO:
- [N/A] Updated changelog.md
=> Remove persist open tasks from Phase endpoint

source/includes/analysis_notes.md, source/includes/changelog.md
=> Add updater + updated fields to Analysis Note endpoint

source/includes/changelog.md, source/includes/connections.md, source/includes/jobs.md
=> Rename group query to group base dn

source/includes/phases.md
Remove persist_open_tasks from payload and response
Refs #SDE-3641
TODO:
=> Remove active from payload

source/includes/changelog.md
Refs #SDE-????
TODO:
- [N/A] Completed documentation for the new endpoint.
=> Add a line about editing SDE phases to changelog

source/includes/changelog.md, source/includes/projects.md
We want this field to be called base not root. See #SDE-4155.
TODO:
=> Rename root to base in projects endpoint.

source/includes/connectors.md
=> Update connector endpoint examples (GET/POST/PUT)

source/includes/applications.md, source/includes/changelog.md, source/includes/projects.md
=> Rename base to base_project for Project endpoint

source/includes/applications.md, source/includes/changelog.md, source/includes/projects.md
=> Refactor task_counts and add incomplete_tasks

source/includes/changelog.md, source/includes/tasks.md
* include parameter for regulation_sections now displays regulations
with description and category
Refs #SDE-4354
TODO:
=> Add docs for API changes for regulations

source/includes/applications.md, source/includes/changelog.md
=> Remove business_unit expand filter in applications

source/includes/applications.md, source/includes/changelog.md, source/includes/connectors.md, source/includes/projects.md
I've pulled what I think are all the v4.8 branches into a new branch we can make release/4.8. Please review @hanifvirani / @sibartlett.
=> Fix release branch 4 8

source/includes/changelog.md, source/includes/tasks.md
Refs #SDE-4497
TODO:
- [/] Set milestone label in pull request (SDE version)
- [/] Updated changelog.md
- [/] Completed documentation for the new endpoint.
- [/] Feature has been merged into SDE develop.
=> Update related tasks result in the Tasks endpoint.

source/includes/applications.md, source/includes/changelog.md
=> Update applications with PATCH

source/includes/changelog.md, source/includes/task_notes.md
=> Task Note Updater Expanded by Default

source/includes/changelog.md, source/includes/user_profile.md
=> Add API changes for UserProfile task notifications

source/includes/applications.md, source/includes/changelog.md
Refs #SDE-4359
TODO:
Emin's edit: checked the last checkbox.
=> Add tags for applications

source/includes/changelog.md
=> Move MALT updates from v4.9 changelog to v4.10

source/includes/alm_connections.md, source/includes/analysis_connections.md, source/includes/api_tokens.md, source/includes/business_units.md, source/includes/changelog.md, source/includes/groups.md, source/includes/introduction.md, source/includes/ldap_connections.md, source/includes/phases.md, source/includes/project_survey.md, source/includes/task_notes.md, source/includes/users.md
We want to discourage people from using the confusing and error prone
PUT operation and instead use PATCH, which makes your intentions
clearer.
TODO:
=> Update all references of PUT to PATCH in our docs.

source/includes/changelog.md, source/includes/phases.md, source/includes/report_settings.md
Add ordering and update the structure of the filters field.
TODO:
Refs: SDE-4825
=> Update docs to reflect changes made for reports pg.

source/includes/alm_connections.md, source/includes/analysis_connections.md, source/includes/changelog.md
=> Add debug_mode flag

source/includes/alm_connections.md, source/includes/changelog.md
=> Add docs for testing ALM connectors & connections

source/includes/changelog.md, source/includes/project_survey.md
* nesting the survey structure twice was redundant
Refs #SDE-4598
TODO:
=> Update Project Survey endpoint

source/includes/changelog.md, source/includes/projects.md
=> Update missing fields on projects endpoint

source/includes/changelog.md, source/includes/tasks.md
Refs SDE-4983
Refs #SDE-????
TODO:
=> Add Docs for Project Tagging

source/includes/jobs.md
=> Fix typos in Jobs documentation

source/includes/glossary_terms.md
=> Document absolute_urls and to_html for Glossary terms 

source/includes/library_problems.md, source/includes/library_tasks.md
=> Document absolute_urls and to_html for Library Tasks and Problems
